Traceback (most recent call last):
  File "migration.py", line 6, in <module>
    from models.products_invoice import ProductsInvoice
  File "/Users/coalchewer/code/src/Robinborg/python/invoice_program/models/products_invoice.py", line 21, in <module>
    Base.metadata.create_all(engine)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/python38/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4785, in create_all
    bind._run_ddl_visitor(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/python38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3110, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/python38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2113, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/python38/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/python38/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 822, in visit_metadata
    collection = sort_tables_and_constraints(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/python38/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 1286, in sort_tables_and_constraints
    dependent_on = fkc.referred_table
  File "/opt/homebrew/Caskroom/miniforge/base/envs/python38/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 3705, in referred_table
    return self.elements[0].column.table
  File "/opt/homebrew/Caskroom/miniforge/base/envs/python38/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/python38/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 2410, in column
    raise exc.NoReferencedTableError(
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'products_invoices.invoice_id' could not find table 'invoices' with which to generate a foreign key to target column 'id'
